[general]
import = [
    "~/.config/alacritty/base16/colors/base16-tomorrow-night.toml"
]

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
